### ISSUE TITLE
Incompatibility on Intel Cherrytrail graphics

### ISSUE THREAD

**Issue by gnsmrky** [01org/caffe#101]
### Issue summary
Testing clcaffe with beignet 1.3.0 (straight apt install) or beignet 1.3.2 (built from latest github source) results in "Aborted (core dumped)" error.  I am trying to make it running with beignet on an Intel Core i3-6006U system so I can rebuild clcaffe using beignet on a cherrytrail (atom z8300) platform.

Have tried many combinations.  Would really like to make it happen with beignet as it's open source OpenCL.

### Steps to reproduce
1. Install beignet 1.3.0 using `sudo apt install beignet*`.  beignet utest only has 1 failure.
2. Build clcaffe linked with icd libOpenCL.so (to switch different OCL libraries by setting icd in /etc/OpenCL/vendors).
`cmake .. -DUSE_GREENTEA=ON -DUSE_CUDA=OFF -DUSE_INTEL_SPATIAL=ON -DBUILD_docs=0 -DUSE_ISAAC=ON -DViennaCL_INCLUDE_DIR=$HOME/local/include -DBLAS=mkl -DOPENCL_LIBRARIES=/usr/lib/x86_64-linux-gnu/libOpenCL.so -DOPENCL_INCLUDE_DIRS=/usr/include`
3. make and make install
4. run the alexnet with -phase TEST
`./tools/caffe time -model ../models/bvlc_alexnet/deploy.prototxt -gpu 0 -phase TEST`

5. It resulted in "Aborted (core dumped)" exception error (from viennacl).

Additional info:
- Have tried to build beignet 1.3.2  (using llvm/clang4.0) from github with same error result
- Using Intel SRB 4.1 OpenCL driver, however, the test ran correctly.  (alexnet inference speed is fast!)
- Again I am using beignet 'cause want to find a way to make clcaffe work on a Cherrytrail platform.  Have made a few attempts on cherrytrail with ISAAC off (ISAAC does not seem to support atom cpu) with beignet and SRB4.1 driver, also resulted in similar error.

### Your system configuration
Operating system: Ubuntu 17.04 and 17.10
Compiler: gcc
CUDA version (if applicable): N/A
CUDNN version (if applicable): N/A
BLAS: MKL
Python or MATLAB version (for pycaffe and matcaffe respectively):

This laptop only has Intel graphics, no discrete graphics.  6GB RAM.

The attached error output was captured by this line:
`./tools/caffe time -model ../models/bvlc_alexnet/deploy.prototxt -gpu 0 -phase TEST 2>core_i3-6006U_caffe_tool_time_alexnet_beignet130_apt_stderr.txt`
[core_i3-6006U_caffe_tool_time_alexnet_beignet130_apt_stderr.txt](https://github.com/01org/caffe/files/1571363/core_i3-6006U_caffe_tool_time_alexnet_beignet130_apt_stderr.txt)

clinfo:
[core_i3-6006U_clinfo_beignet130_apt.txt](https://github.com/01org/caffe/files/1571350/core_i3-6006U_clinfo_beignet130_apt.txt)

caffe device_query:
[core_i3-6006U_caffe_device-query.txt](https://github.com/01org/caffe/files/1571381/core_i3-6006U_caffe_device-query.txt)

**Comment by gongzg** [comment]
You reported two issues actually. The first is related to Beignet, and the second is related to CHT support.
For beignet issue, I have to advice you to switch to official OpenCL driver. The good news is that the open source version of official OpenCL driver is coming.
For CHT support, you can try latest SRB5.0 driver and set the following envorinment variable ：
export CLCAFFE_IGNORE_PRETUNE=1
before you run your application.  And please don't use FP16 on CHT platform which is not supported due to OpenCL driver issue.

**Comment by acervr** [comment]
Nice to hear the official OpenCL driver will open source soon!  Crossing fingers on better support level on BYT & CHT.

I have tried both SRB4.1 and 5.0 on CHT.  Alexnet test ran through with ~340ms in each forward cycle with -phase TEST.  So good sign there.  

However, when testing Mobilenet SSD (had to comment out engine: CAFFE in prototxt and set_mode_gpu() in python), the objects being detected are all random (all randomly detected to upper part of the image).  When using CPU mode or OpenCL CPU, everything works correctly.  This is weird.  I would assume that's the precision issue related to FP16 you mention.  This symptom does not happen on Core i3.

How exactly do you disable FP16?  Look at the make files it does seem like disabling ISAAC would implicitly turn off "half floating point", which was what I did on CHT.  Or do I need to disable it in cl_headers explicitly?

**Comment by gnsmrky** [comment]
Nice to hear the official OpenCL driver will open source soon!  Crossing fingers on better support level on BYT & CHT.

I have tried both SRB4.1 and 5.0 on CHT.  Alexnet test ran through with ~340ms in each iteration cycle with -phase TEST.  So good sign there.  

However, when testing Mobilenet SSD (had to comment out engine: CAFFE in prototxt and set_mode_gpu() in python), the objects being detected are all random (all randomly detected to upper part of the image).  When using CPU mode or OpenCL CPU, everything works correctly.  This is weird.  I would assume that's the precision issue related to FP16 you mention.  This symptom does not happen on Core i3.

How exactly do you disable FP16?  Look at the make files it does seem like disabling ISAAC would implicitly turn off "half floating point", which was what I did on CHT.  Or do I need to disable it in cl_headers explicitly?

**Comment by gnsmrky** [comment]
Screenshots using Intel SRB 5.0 driver on CHT.  In python using the following code to select gpu device:
`caffe.set_mode_gpu()`
`caffe.set_device(0) # 0 for GPU.  1 for CPU`

**- Using GPU0 (device 0, the GPU device):** the result is incorrect.  Seems like all objects are being detected and grouped at upper part of the image.
![20171221_clcaffe_intel-srb50-gpu0_mobilenet-ssd_incorrect](https://user-images.githubusercontent.com/18223627/34253714-b7dd1a5c-e683-11e7-9cdc-9dfe2f7de3df.png)
**- Using GPU1 (device 1, the CPU device):**  the result is good, albeit it takes much longer (~30x longer).
![20171221_clcaffe_intel-srb50-gpu1_mobilenet-ssd_correct](https://user-images.githubusercontent.com/18223627/34253725-c22b9d6c-e683-11e7-94ee-ff1c8d9eac92.png)

As the CPU device results in correct object detection.  Is the incorrect result should be due to the GPU using FP16?  Running out of ideas here.  Need help...

**clinfo output:**
[clinfo_atom_z8300_intel_srb50.txt](https://github.com/01org/caffe/files/1578988/clinfo_atom_z8300_intel_srb50.txt)

**Comment by gongzg** [comment]
@gnsmrky Is it on Linux or Windows? Did you try this your i3?

**Comment by gongzg** [comment]
@gnsmrky you can try 0b05dc522d4a1a6b730eceda76c0583845bd7175 firstly.

**Comment by gnsmrky** [comment]
The screen shots were from CHT (atom z8300) on Linux.  Tried both Ubuntu 16.04 and 17.04 yielded the same result.

Just took a look at the `0b05dc5`.  Both files (for FFT?) are already in place (git cloned the latest just last night).

**Comment by gongzg** [comment]
The latest code has some change in the depthwise layer which is related to MobileNetSSD which may bring regression on CHT platform, so I suggest you try 0b05dc5 to see whether it work.

**Comment by gnsmrky** [comment]
Yes I am trying that now.  As the patch is mainly for FFT, should I also add USE_FFT when doing cmake?

**Comment by gongzg** [comment]
No, please don't change build option. You can also try to set the following environment variable before run the application:
export CLCAFFE_IGNORE_PRETUNE=1

**Comment by gnsmrky** [comment]
Just tried `0b05dc5`.  Unfortunately, it didn't work and resulted the same "upper green grouped" detections using mobilenet ssd.

The following cmake was used (had to set ISAAC to OFF to avoid exception error on CHT).
`cmake .. -DUSE_GREENTEA=ON -DUSE_CUDA=OFF -DUSE_INTEL_SPATIAL=ON -DBUILD_docs=0 -DUSE_ISAAC=OFF -DViennaCL_INCLUDE_DIR=$HOME/local/include -DBLAS=mkl -DOPENCL_LIBRARIES=/usr/lib/x86_64-linux-gnu/libOpenCL.so -DOPENCL_INCLUDE_DIRS=/usr/include`

`export CLCAFFE_IGNORE_PRETUNE=1` was set before the python execution.

Result image:
![20171222_clcaffe-0b05dc5_intel-srb50-gpu0_mobilenet-ssd_incorrect](https://user-images.githubusercontent.com/18223627/34293707-a167c1d8-e740-11e7-8cd2-da7a1baf979c.png)

Python run script outputs:
[20171222_clcaffe_0b05dc5_noisaac_mobilenet-ssd_stdout.txt](https://github.com/01org/caffe/files/1582117/20171222_clcaffe_0b05dc5_noisaac_mobilenet-ssd_stdout.txt)
[20171222_clcaffe_0b05dc5_noisaac_mobilenet-ssd_stderr.txt](https://github.com/01org/caffe/files/1582118/20171222_clcaffe_0b05dc5_noisaac_mobilenet-ssd_stderr.txt)

**Comment by gnsmrky** [comment]
Changed the title to better reflect this issue...

**Comment by gongzg** [comment]
Unfortunately, I don't have a CHT machine, so I can't reproduce this issue. One more thing we can try is to enable ISAAC. I will update ISAAC next week to make it support CHT. After that you can give a try.

**Comment by gnsmrky** [comment]
Ok.  Will wait for the new ISAAC...

BTW, how do you disable FP16?  I want to give that a shot.

**Comment by gongzg** [comment]
From the log, you are using FP32 already.

**Comment by gongzg** [comment]
You can check caffe-fp16.cpp/caffe.cpp to find out how to enable fp16.

**Comment by gnsmrky** [comment]
Did few more tests.

**1. gtest_filter test**
`./test/test.testbin  --gtest_filter=*OpenCLKernelCompileTest* 0`

Result: 
![20171222_clcaffe-0b05dc5_intel-srb50-gpu0_gtest_filter_result](https://user-images.githubusercontent.com/18223627/34295266-6c4bc7cc-e747-11e7-86c4-b0e53b8b61f0.png)

Test output: (many warnings)
[20171222_clcaffe_0b05dc5_gtest_filter_stdout.txt](https://github.com/01org/caffe/files/1582297/20171222_clcaffe_0b05dc5_gtest_filter_stdout.txt)
[20171222_clcaffe_0b05dc5_gtest_filter_stderr.txt](https://github.com/01org/caffe/files/1582298/20171222_clcaffe_0b05dc5_gtest_filter_stderr.txt)


**2. make runtest**
Result:  6 failed tests. It's odd that even CPU device has failed result (  from caffe::CPUDevice(double)  )
![20171222_clcaffe_0b05dc5_intel-srb50-gpu0_make_runtest_result](https://user-images.githubusercontent.com/18223627/34295814-4d4e17be-e74a-11e7-9b7b-dd423523923b.png)

Test output:
[20171222_clcaffe_0b05dc5_make_runtest_stderr.txt](https://github.com/01org/caffe/files/1582287/20171222_clcaffe_0b05dc5_make_runtest_stderr.txt)
[20171222_clcaffe_0b05dc5_make_runtest_stdout.txt](https://github.com/01org/caffe/files/1582288/20171222_clcaffe_0b05dc5_make_runtest_stdout.txt)

**Comment by gongzg** [comment]
I just pushed a patch to github.com/intel/isaac to support more Intel platforms. Please give a try.

**Comment by gongzg** [comment]
The softmaxLayer test failure is weird and may be harmful for normal use cases. The other failures are not very important for inference work loads. You can try to fallback to CPU device for softmax layer and softmaxwithloss layer to check whether you can get correct deteciton result.

**Comment by gongzg** [comment]
Or just apply the following patch to fallback to non-subgroup implementation for those two layers.

diff --git a/src/caffe/layers/softmax_layer.cu b/src/caffe/layers/softmax_layer.cu
index 801639b..a86351c 100644
--- a/src/caffe/layers/softmax_layer.cu
+++ b/src/caffe/layers/softmax_layer.cu
@@ -146,7 +146,7 @@ void SoftmaxLayer<Dtype>::Forward_gpu(const vector<Blob<Dtype>*>& bottom,
       return;
     viennacl::ocl::context &ctx = viennacl::ocl::get_context
                                     (this->device_->id());
-    if (this->device_->CheckCapability("cl_intel_subgroups")
+    if (0 && this->device_->CheckCapability("cl_intel_subgroups")
         && inner_num_ < 128) {
       viennacl::ocl::program &program = this->device_->template program<Dtype>();
       viennacl::ocl::kernel *oclk_softmax_forward_kernel;
diff --git a/src/caffe/layers/softmax_loss_layer.cu b/src/caffe/layers/softmax_loss_layer.cu
index 0fd73e5..6865a3e 100644
--- a/src/caffe/layers/softmax_loss_layer.cu
+++ b/src/caffe/layers/softmax_loss_layer.cu
@@ -98,7 +98,7 @@ void SoftmaxWithLossLayer<Dtype>::Forward_gpu(
                                   ignore_label_, WrapHandle(counts, &ctx)),
         ctx.get_queue());

-    if (this->device_->CheckCapability("cl_intel_subgroups")) {
+    if (0 && this->device_->CheckCapability("cl_intel_subgroups")) {
       viennacl::ocl::kernel &oclk_softmax_loss_forward_asum =
         program.get_kernel(
           CL_KERNEL_SELECT("softmax_loss_forward_asum"));

**Comment by gnsmrky** [comment]
I have tried to hard code the isaac device.cpp to default to skylake and broadwell over the weekend and it produced the same "upper green group boxes" result.

Trying the non-subgroup patch now...

**Comment by gnsmrky** [comment]
Resulted the same "upper green grouped boxes" error.  The following were used:
1. Up-to-date inference-optmized branch.
2. ISAAC was being used (default to skylake).
3. `export CLCAFFE_IGNORE_PRETUNE=1` was set.  
4. The patch for softmax_layer.cu and softmax_loss_layer.cu

`make runtest` resulted in `Fatal error: Intel iGPU device found but doesn't support cl_intel_subgroups_short.` error.  This is odd.  I am rebuilding (make clean and deleting build folder) and give it another try.

Will also try the `0b05dc5` commit with patches for softmax_layer.cu and softmax_loss_layer.cu

**Comment by gnsmrky** [comment]
@gongzg Good news!  It's working!  with `0b05dc5` commit and the patches for `softmax_layer.cu` and `softmax_loss_layer.cu`, it is now detecting objects correctly using Mobilenet SSD!  (Still curious why these 2 layers fail, though...)

The speed is amazing, as expected, net.forward() at about 0.1s per frame!  Considering this is a lower spec end of Cherrytrail (z8300), this is just amazing to see how this little guy can do such fast inference speed!  Thanks for all the help!

![20171225_clcaffe_srb50_good_01](https://user-images.githubusercontent.com/18223627/34341045-5065fd54-e9ca-11e7-82cb-375cb2e5531c.png)
![20171225_clcaffe_srb50_good_02](https://user-images.githubusercontent.com/18223627/34341049-55b06a4c-e9ca-11e7-8d9e-9c0297d15fb7.png)

I am gonna try out caffe-fp16 next and see if cherrytrail plays nice with FP16.

**Comment by gongzg** [comment]
That's really great! The CHT driver has some known issues as below:
1. Some of the sub group APIs have bugs which are used in the two softmax layers.
2.  Lack of sub group extension with half support thus no need to try FP16.

**Comment by gnsmrky** [comment]
Ok got it.  

BTW, here is the cpuid output for atom z8300.  Just FYI so the official patches for ISAAC (device.cpp) and softmax layers can be put in place.

`cpuid | brand` output:
![screenshot from 2017-12-26 10-52-11](https://user-images.githubusercontent.com/18223627/34345703-ea0d90dc-ea2b-11e7-8ce8-7bd9aeebe9ee.png)

`cpuid > cht_atom_z8300_cpuid.txt` output:
[cht_atom_z8300_cpuid.txt](https://github.com/01org/caffe/files/1586456/cht_atom_z8300_cpuid.txt)

**Comment by gongzg** [comment]
Thanks for the information. I will cook a patch for CHT atom devices for both ISAAC and clcaffe latter.
BTW, did you try the layer fusion method?

**Comment by gnsmrky** [comment]
Fused model is exactly what I am going to try next (as FP16 isn't worth trying).  Will come back with the layer fusion method.

**Comment by gnsmrky** [comment]
Here comes the layer fusion model result (left terminal).  It's about 10% faster (~0.01s faster) than non-fused mode.  Still worth it as it's a one-time conversion for the models.

![screenshot from 2017-12-26 14-35-25](https://user-images.githubusercontent.com/18223627/34355421-25ec46f4-ea70-11e7-9f4a-151d3d13d365.png)

**Comment by liyuming1978** [comment]
@gnsmrky would you please try:
 ./build/tools/caffe time -phase TEST -gpu 0 -model  (your prototxt file path)
I test in J3455,   the mobilenet-ssd only  155ms. (while you 100ms...) with 4.1 cl driver
I switch to 5.0 driver,  it speed up to 149ms , but still lower than your's 100ms.
I think J3455 should be faster than cherrytrail

**Comment by gnsmrky** [comment]
@liyuming1978 actually my result was for Mobilenet-SSD (https://github.com/chuanqi305/MobileNet-SSD) net forward speed with fused model, not the "caffe time alexnet deploy" benchmark.

`./tools/caffe time -model ../models/bvlc_alexnet/deploy.prototxt -gpu 0 -phase TEST` on Cherrytrail (z8300) is only about 340~350ms per iteration.  So your J3455 (apollo lake) reaches ~150ms makes sense as the EUs are being clocked at a much higher frequency.

What you can try is to use caffe-fp16, which should give you close to 30% performance boost.  Let us know if it has better result.

**Comment by gnsmrky** [comment]
Posting the caffe time test/benchmark result for Cherrytrail (z8300)

1. GPU result using `./tools/caffe time -model ../models/bvlc_alexnet/deploy.prototxt -phase TEST -gpu 0 `
![screenshot from 2017-12-29 17-21-18](https://user-images.githubusercontent.com/18223627/34433861-15a1adf8-ecbd-11e7-9f88-583644ed960a.png)

2. CPU result using `./tools/caffe time -model ../models/bvlc_alexnet/deploy.prototxt -phase TEST`
![screenshot from 2017-12-29 17-23-27](https://user-images.githubusercontent.com/18223627/34433871-24667954-ecbd-11e7-978c-f6424c455b0b.png)

**Comment by liyuming1978** [comment]
@gnsmrky , the 100ms is the time of my test in APL for mobilenet-ssd! the prototxt file is from https://github.com/liyuming1978/caffe_example/blob/master/Model/MobileNetSSD/MobileNetSSD_deploy_fuse.prototxt
the different (https://github.com/chuanqi305/MobileNet-SSD) is chuanqi305 will he use engine:CAFFE for dw conv, while I use the default which clcaffe enabled. 
so if possible, would you please share your prototxt?  so I can test in APL,  I just think your speed is so quick!  so I want to find the reason.

**Comment by liyuming1978** [comment]
caffe time can be also used to test   mobilenet-ssd  .your alexnet speed is looks to be ok.  but  mobilenet-ssd looks to be too quick

**Comment by gongzg** [comment]
@liyuming1978 J3455 and Z8300 both have 12 EU. J3455's GPU boost frequency is higher than Z8300 (750MHz vs 500Mhz). If your J3455 can really boost to 750MHz, then it should get better performance. But in practice, we also noticed that the APL platform could not get expected performance. I already contacted the OCL driver team to investigate this issue.

**Comment by liyuming1978** [comment]
@gongzg  how to get the real  GPU boost frequency in real-time?

**Comment by gnsmrky** [comment]
@liyuming1978 Here is the prototxt I used.  Didn't do much but simply removed (commented out) all "engine:Caffe".  Simply do a global search of "engine: Caffe" and replace it with "#engine: Caffe" should do it.

[MobileNetSSD_deploy.no_engine.prototxt.zip](https://github.com/01org/caffe/files/1596841/MobileNetSSD_deploy.no_engine.prototxt.zip)

I timed the `demo.py` file's net forward as the following.  Again, not much different from the original demo.py at Mobilenet SSD (https://github.com/chuanqi305/MobileNet-SSD).
![screenshot from 2018-01-02 12-16-42](https://user-images.githubusercontent.com/18223627/34474263-ba49ed00-efb7-11e7-928f-5fdfffd86a40.png)

One possible reason may be that you didn't set USE_INTEL_SPATIAL during build.  That actually slows things down quite a bit.  On CHT, it's about 0.3s ~ 0.4s per forward on Mobilenet SSD.  You will never go back once you do USE_INTEL_SPATIAL.

Hope this helps...

**Comment by liyuming1978** [comment]
@gnsmrky   I compile with  cmake .. -DUSE_GREENTEA=ON -DUSE_CUDA=OFF -DUSE_INTEL_SPATIAL=ON -DBUILD_docs=0 -DUSE_ISAAC=ON -DViennaCL_INCLUDE_DIR=$HOME/local/include -DOPENCL_LIBRARIES=/opt/intel/opencl/libOpenCL.so -DOPENCL_INCLUDE_DIRS=/opt/intel/opencl/include

so,  DUSE_INTEL_SPATIAL=ON ,  as zhigang says,  that maybe the ocl driver issue  for J3455...

**Comment by twmht** [comment]
@gnsmrky 

How did you get 0.1s per image? Did you try the fused version or fp16?

**Comment by gnsmrky** [comment]
@twmht USE_INTEL_SPATIAL is the key.  It gives you about 3~4 x performance gain.

FP16 does not work on CHT platform.  I tried, but it just results in run-time exception errors.  0.1s per forward iteration is good enough for my use case.  So I didn't dig in further.  But should FP16 work, it may have another 50% gain and lower the forward time to 0.05s ~ 0.07s, I guess.

**Comment by twmht** [comment]
@gnsmrky 

Have you ever set 

```
caffe.set_mode_gpu()
caffe.set_device(0)
```

in the demo script?

**Comment by gnsmrky** [comment]
@twmht 
yes, I have these 2 lines.  Pls see my previous comment:
[https://github.com/01org/caffe/issues/101#issuecomment-353327987](https://github.com/01org/caffe/issues/101#issuecomment-353327987)

**Comment by twmht** [comment]
@gnsmrky 

one more question,  I am working on CHT too. but the opencl driver only recognize GPU, no CPU is detected.

I have installed SRB 4.1 OpenCL driver, here is my clinfo.

[cht_clinfo.txt](https://github.com/01org/caffe/files/1645214/cht_clinfo.txt)

Any suggestion?

**Comment by gnsmrky** [comment]
@twmht 
Did you also install the files from the `intel-opencl-cpu-r4.1-61547.x86_64.tar.xz` package?  This should include the CPU device driver for OpenCL.
