### ISSUE TITLE
Does Intel caffe support the GPU mode?

### ISSUE THREAD

**Issue by gyfscx** [01org/caffe#103]
# Does the performance of the GPU mode are the same as the official caffe?

### Your system configuration
Operating system: win 10
Compiler: vs 2015
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
BLAS: open/mkl
Python or MATLAB version (for pycaffe and matcaffe respectively): 3.5

**Comment by gongzg** [comment]
The official Caffe doesn't support FP16 and layer fusion yet. So for some models, thie branch is much faster than the upstream Caffe.
