### ISSUE TITLE
minor mistakes in the wiki of clCaffe

### ISSUE THREAD

**Issue by dongx1x** [01org/caffe#104]
1. Link of MKL can not be accessed, http://softwareproducts.intel.com/ILC/.
2. In section [yolo2-model-suppor](https://github.com/01org/caffe/wiki/clCaffe#yolo2-model-support), `python tools/inference-optimize/model_fuse.py --indefinition yolo416/yolo_deploy.prototxt --outdefinition yolo416/fused_yolo_deploy.prototxt --inmodel yolo416/yolo.caffemodel --outmodel yolo416/fused_yolo.caffemodel` **should be** `python tools/inference-optimize/model_fuse.py --indefinition models/yolo/yolo416/yolo_deploy.prototxt --outdefinition models/yolo/yolo416/fused_yolo_deploy.prototxt --inmodel models/yolo/yolo416/yolo.caffemodel --outmodel models/yolo/yolo416/fused_yolo.caffemodel`.
3. Add some commands for installing OpenCL driver is appreciated.
Thanks!

**Comment by gongzg** [comment]
Thanks for reporting these issues. Already fixed.

**Comment by willshw** [comment]
Item 2, has not been corrected.
