### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

### ISSUE THREAD

**Issue by twmht** [01org/caffe#107]
### Issue summary
when doing inference with mobilenet-ssd with pycaffe , it throws erros when forwarding.

```
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.
```

I have added the path of libmkl_mc3.so and libmkl_def.so to `LD_LIBRARY_PATH`,  but it still does not work.

I use opencl as the backend, and with intel atom z8300.

`import caffe`  and `Network init` is fine, but having this problem when forwarding.

### Steps to reproduce
there is a demo script (https://github.com/chuanqi305/MobileNet-SSD) I used.

### Your system configuration
Operating system: ubuntu 16.04
Compiler: gcc 5.4/0
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): pyhon 2.7.12

Any suggestion?

**Comment by gnsmrky** [comment]
Try export the following before executing clcaffe.
'export LD_PRELOAD=/opt/intel/mkl/lib/intel64/libmkl_core.so:/opt/intel/mkl/lib/intel64/libmkl_sequential.so'

**Comment by twmht** [comment]
thanks!
