### ISSUE TITLE
Error: "extra_build_options_" was not declared in this scope

### ISSUE THREAD

**Issue by xhuan28** [01org/caffe#109]
We developed a ROS project based on clCaffe as backend. One user find a build issue with your latest commit(https://github.com/01org/caffe/commit/3eb1dfdc87f24a19c2c7aa66ffcac6ca27a30d1f). The issue details are [here](https://github.com/intel/ros_opencl_caffe/issues/3). 
From your latest commit, you defined a variable called "extra_build_options_" which is embraced by the Macro "USE_GREENTEA", but the function "std::string get_extra_build_options(void) { return extra_build_options_; }" isn't embraced by the Macro. I think it is the cause of the build issue.
Could you look into this and fix it?

**Comment by gongzg** [comment]
fixed, please check.

**Comment by xhuan28** [comment]
@gongzg  Thanks, Zhigang. Our problem has been addressed.
