### ISSUE TITLE
cmake scripts define USE_CLBLAS when using OpenBLAS

### ISSUE THREAD

**Issue by psprashX** [01org/caffe#28]
Hi, I get the below error when running make on the clCaffe branch. 
.../workspace/clCaffe/caffe/src/caffe/common.cpp:24:54: fatal error: clBLAS.h: No such file or directory
     #include <clBLAS.h>                     // NOLINT
                                                      ^
compilation terminated.
[  2%] Building CXX object src/caffe/CMakeFiles/caffe.dir/device.cpp.o
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1

I verified that CMakeCache.txt contains,
//Selected BLAS library
BLAS:STRING=open
...
//Build Caffe with clBLAS support (instead of using ViennaClBLAS)
USE_CLBLAS:BOOL=OFF

The issue seems to be with the below code in  caffe/cmake/Dependencies.cmake
if (USE_ISAAC)
  find_package(ISAAC)
  if (NOT ISAAC_FOUND)
    message(FATAL_ERROR "ISAAC required but not found.")
  endif()
  list(APPEND Caffe_LINKER_LIBS PUBLIC ${ISAAC_LIBRARY})
  list(APPEND Caffe_DEFINITIONS PUBLIC -DUSE_CLBLAS)  <<<<
endif()

should possibly be

if (USE_ISAAC)
  find_package(ISAAC)
  if (NOT ISAAC_FOUND)
    message(FATAL_ERROR "ISAAC required but not found.")
  endif()
  list(APPEND Caffe_LINKER_LIBS PUBLIC ${ISAAC_LIBRARY})
  if (USE_CLBLAS)
    list(APPEND Caffe_DEFINITIONS PUBLIC -DUSE_CLBLAS)
  endif()
endif()

**Comment by atlury** [comment]
Use the official opencl branch, I have tested it and it works!
