### ISSUE TITLE
when I run a model, how can I know that I run it on the OpenCL backend rather than CPU mode?

### ISSUE THREAD

**Issue by JulyJohn** [01org/caffe#77]
when I run a model, how can I know that I run it on the OpenCL backend rather than CPU mode?

such as, when I run the mnist example, I got a log like this:

```
xx@xx-B150M-D3H:~/code/clCaffe$ sudo time sh examples/mnist/train_lenet.sh -gpu 0
I1104 11:50:31.627620 26067 device.cpp:72] CL_DEVICE_HOST_UNIFIED_MEMORY: 1
I1104 11:50:31.631078 26067 caffe.cpp:262] Using GPUs 0
I1104 11:50:31.631204 26067 solver.cpp:53] Initializing solver from parameters: 
test_iter: 100
test_interval: 500
base_lr: 0.01
display: 100
max_iter: 1000
lr_policy: "inv"
gamma: 0.0001
power: 0.75
momentum: 0.9
weight_decay: 0.0005
snapshot: 5000
snapshot_prefix: "examples/mnist/lenet"
solver_mode: GPU
device_id: 0
net: "examples/mnist/lenet_train_test.prototxt"
train_state {
  level: 0
  stage: ""
}
```

so, I'm using the OpenCL as backend now?

**Comment by gongzg** [comment]
I1104 11:50:31.627620 26067 device.cpp:72] CL_DEVICE_HOST_UNIFIED_MEMORY: 1
I1104 11:50:31.631078 26067 caffe.cpp:262] Using GPUs 0

indicates you are using GPU device 0.

You can use build/tools/caffe device_query to check how many GPU devices the platform have.
