### ISSUE TITLE
extremely slow using Intel iGPU

### ISSUE THREAD

**Issue by bxk-sonavex** [01org/caffe#80]
This issue is initially posted at https://github.com/BVLC/caffe/issues/5099#issuecomment-342865849.  Here should be the correct place to discuss this issue.  Below are the issue and some discussions in the above mentioned place.

When running the tests, I got a whole bunch of errors like (may not catch all of them)
```
C:\DL\clCaffe\src\caffe\test\test_argmax_layer.cpp(132): error : Expected: (bottom_data[i * dim + j]) <= (max_val), actual: -0.402832 vs -0

C:\DL\clCaffe\src\caffe\test\test_convolution_layer_spatial.cpp(735): error : The difference between top_data[i] and ref_top_data[i] is 1.8
077674604790599e+28, which exceeds delta, where [C:\DL\clCaffe\build\src\caffe\test\runtest.vcxproj]
  top_data[i] evaluates to -1.8077674604790599e+28,
  ref_top_data[i] evaluates to 7.1034564971923828, and
  delta evaluates to 9.9999997473787516e-05.

C:\DL\clCaffe\src\caffe\test\test_convolution_layer_spatial.cpp(735): error : The difference between top_data[i] and ref_top_data[i] is 1
.803808228419822e+28, which exceeds delta, where [C:\DL\clCaffe\build\src\caffe\test\runtest.vcxproj]

    2418 Warning(s)
    17672 Error(s)

Time Elapsed 00:10:25.65
ERROR: Tests failed
```
Should these errors be concerned?

Anyway, I am testing the build using the mnist example.  It's **extremely slow**, even much much slower than the original Caffe using CPU.  And there are some warnings (repeated several times)
```
warning: Linking two modules of different data layouts: '' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024' whereas '<origin>' is 'e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32:64'

warning: Linking two modules of different target triples: ' is 'spir64' whereas '<origin>' is 'vISA_64'
```
Any idea?

==============================================================
https://github.com/BVLC/caffe/issues/5099#issuecomment-342920090

@gongzg Just want to update you with the performance
CPU: 7 minutes 33 seconds, accuracy = 0.9914
GPU: 29 minutes 34 seconds, accuracy = 0.8406

Wondering what is the performance on Linux. Then, I could have a basic idea on how much speed up using Intel GPU (OpenCL) vs CPU. Thanks!!

===============================================================
https://github.com/BVLC/caffe/issues/5099#issuecomment-342930192

Ben you will need to include INTEL_SPATIAL for all convolutional layers in your deploy.proto. I have personally tested it in real time in linux.

#5165

"I have tested on an Intel tv stick, webcam using Intel Spatial kernels and using 19-layer vgg model. I am able to get real time classification and all under 3.5 watts"

Windows should also work.

===============================================================
https://github.com/BVLC/caffe/issues/5099#issuecomment-343001347

for the issue on 01org version, please open an issue there. There are some test failures due to FP16 precision issue on those gradient test cases which is not critical. The performance is extremely slow which should be caused by the auto-tuning. It should be much faster when you run it again. You can firstly try to use the build/tools/caffe to measure the forward performance for AlexNet.

**Comment by bxk-sonavex** [comment]
@gongzg I tested AlexNet using 
```
build\tools\Release\caffe.exe time -model=models\bvlc_alexnet\deploy.prototxt -gpu 0
```
Without INTEL_SPATIAL (using the deploy.prototxt directly), the benchmark result is
```
...
I1109 14:10:08.778888  5932 caffe.cpp:581] Iteration: 50 forward-backward time: 281.921 ms.
I1109 14:10:08.778888  5932 caffe.cpp:598] Average Forward pass: 125.854 ms.
I1109 14:10:08.778888  5932 caffe.cpp:600] Average Backward pass: 0 ms.
I1109 14:10:08.778888  5932 caffe.cpp:602] Average Forward-Backward: 567.526 ms.
I1109 14:10:08.778888  5932 caffe.cpp:604] Total Time: 28376.3 ms.
I1109 14:10:08.778888  5932 caffe.cpp:605] *** Benchmark ends ***
```

With INTEL_SPATIAL by adding `engine: INTEL_SPATIAL` in all the `convolution_param`s in the deploy.prototxt, the result is
```
...
I1109 14:38:14.139897 10164 caffe.cpp:598] Average Forward pass: 127.539 ms.
I1109 14:38:14.139897 10164 caffe.cpp:600] Average Backward pass: 0 ms.
I1109 14:38:14.139897 10164 caffe.cpp:602] Average Forward-Backward: 892.545 ms.
I1109 14:38:14.139897 10164 caffe.cpp:604] Total Time: 44627.3 ms.
I1109 14:38:14.139897 10164 caffe.cpp:605] *** Benchmark ends ***
```

As you can see, the average forward are quite the same.  Seems the INTEL_SPATIAL did not boost up the speed.  In addition, using INTEL_SPATIAL took much longer total time.

**Comment by bxk-sonavex** [comment]
FYI.  There were some warnings and hope those did not cause the slow.
```
I1109 14:37:29.506239 10164 caffe.cpp:531] *** Benchmark begins ***
I1109 14:37:29.506239 10164 caffe.cpp:532] Testing for 50 iterations.
warning: Linking two modules of different data layouts: '' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024' whereas '<origin>' is 'e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32:64'

warning: Linking two modules of different target triples: ' is 'spir64' whereas '<origin>' is 'vISA_64'

warning: Linking two modules of different data layouts: '' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024' whereas '<origin>' is 'e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32:64'

warning: Linking two modules of different target triples: ' is 'spir64' whereas '<origin>' is 'vISA_64'

warning: Linking two modules of different data layouts: '' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024' whereas '<origin>' is 'e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32:64'

warning: Linking two modules of different target triples: ' is 'spir64' whereas '<origin>' is 'vISA_64'

warning: Linking two modules of different data layouts: '' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024' whereas '<origin>' is 'e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32:64'

warning: Linking two modules of different target triples: ' is 'spir64' whereas '<origin>' is 'vISA_64'

I1109 14:38:01.158298 10164 caffe.cpp:581] Iteration: 1 forward-backward time: 31647.6 ms.
```

**Comment by bxk-sonavex** [comment]
@gongzg In addition to build and test the code, I would like to help on developing a working version.  Let me know if anything I could help.  Thanks!

**Comment by gongzg** [comment]
@bxk-sonavex Did you see those warning messages everytime when you run the same benchmark? And you can add a "-phase TEST" option to the command line to get better performance for inference only. The INTEL_SPATIAL will be enabled by default when you compile clcaffe with INTEL_SPATIAL support, so you don't need to modify the prototxt manually, and if you do, it should be the same. You can compare the performance with CPU device if you want to check the acceleration compare to CPU.

**Comment by gongzg** [comment]
Those warning messages are from the OpenCL compiler and is harmless. As by default, clCaffe will cache the previous compiled kernel, the second run should not have those message.

**Comment by bxk-sonavex** [comment]
- Yes, those warning messages were there every time when running the same benchmark.  However, when using "-phase TEST", the messages were gone.
- GPU was about 5x faster than CPU.  When using "-phase TEST", GPU is about 10x faster than CPU.

Does the performance number below make sense to you?
```
build\tools\Release\caffe.exe time -model=models\bvlc_alexnet\deploy.prototxt -phase TEST -gpu 0

I1109 14:37:28.623131 10164 caffe.cpp:500] Use GPU with device ID 0
I1109 14:37:28.841903 10164 device.cpp:72] CL_DEVICE_HOST_UNIFIED_MEMORY: 1
I1109 14:37:28.857537 10164 net.cpp:57] Initializing net from parameters:
name: "AlexNet"
...
I1109 22:49:23.288153  5504 caffe.cpp:515] Performing Forward
I1109 22:49:23.684371  5504 caffe.cpp:520] Initial loss: 0
I1109 22:49:23.684371  5504 caffe.cpp:531] *** Benchmark begins ***
I1109 22:49:23.685359  5504 caffe.cpp:532] Testing for 50 iterations.
I1109 22:49:23.733492  5504 caffe.cpp:581] Iteration: 1 forward-backward time: 47.2212 ms.
...
I1109 22:49:25.988559  5504 caffe.cpp:581] Iteration: 50 forward-backward time: 44.2227 ms.
I1109 22:49:25.988559  5504 caffe.cpp:598] Average Forward pass: 45.3224 ms.
I1109 22:49:25.989583  5504 caffe.cpp:600] Average Backward pass: 0 ms.
I1109 22:49:25.989583  5504 caffe.cpp:602] Average Forward-Backward: 46.0705 ms.
I1109 22:49:25.990566  5504 caffe.cpp:604] Total Time: 2303.53 ms.
I1109 22:49:25.990566  5504 caffe.cpp:605] *** Benchmark ends ***
```

**Comment by gongzg** [comment]
@bxk-sonavex The performance looks good for me. And as to the issue you found when you try mnist training, I just pushed some patches which could fix them and you should get the same accuracy on GPU now.  The compiler message should only print once for a specific net model, as the second time there will be a cached kernel. That's should be another issue anyway. Will look into that next week.

**Comment by bxk-sonavex** [comment]
@gongzg Thanks for your great help!!  Will test the latest repo and keep you updated.

I found another issue.  Sometimes, `caffe time` printed out a lot of unreadable characters and then crashed.  Then, immediately running it the second time, there were no problem at all and produced similar performance as reported above.  It looks sort of random for me.
  
Probably should open another issue and discuss it there?

**Comment by gongzg** [comment]
As to the performance you got now is normal and much faster than CPU, I'm going to close this issue. As to the other issues you mentioned (mnist accuracy and caffe time issue), please update to the latest code and test again. If you found any new issue, feel free to open a new one.
