### ISSUE TITLE
if run firstly in cpu mode then switch to gpu mode. opencl  fail

### ISSUE THREAD

**Issue by liyuming1978** [01org/caffe#83]
### Your system configuration
Operating system: Windows & Linux
Compiler: vs2015(windows) and gcc for linux
CUDA version (if applicable): no
CUDNN version (if applicable): no
BLAS: atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):

都是默认配置编译的clcaffe,  发现先在cpu mode, 推理一遍后, 再切换到gpu mode推理 ,error
伪代码:
Caffe::set_mode(Caffe::CPU);    
net_.reset(new Net<float>(model_file, TEST, Caffe::GetDefaultDevice()));
net_.reset(new Net<Dtype>(model_file, TEST, Caffe::GetDefaultDevice()));
...
net_->Forward();
Caffe::set_mode(Caffe::GPU);
Caffe::SetDevice(gpus[0]);
...
net_->Forward(); //error

**Comment by gongzg** [comment]
This is not a bug but a usage problem. The usage of clCaffe is to set devices firstly:
Caffe::SetDevice(gpus[0]);

After that you can create a new net model, then you can set_mode to CPU to run on CPU device. After that you can call set_mode to GPU then it will switch to GPU.

**Comment by liyuming1978** [comment]
got it!. net will create with default device (set by code), if changing device , must re-new net.
