### ISSUE TITLE
Symbol lookup error at run time

### ISSUE THREAD

**Issue by Bidski** [01org/caffe#92]
When loading a binary linked to `libcaffe.so.1.0.0-rc5`, the following error is displayed

```
symbol lookup error: libcaffe.so.1.0.0-rc5: undefined symbol: _ZN5caffe19ConvolutionLayerFFTIN10half_float4halfEE15Forward_gpu_fftERKSt6vectorIPNS_4BlobIS2_EESaIS7_EESB_
```

Using c++filt to demangle the symbol gets us

```
caffe::ConvolutionLayerFFT<half_float::half>::Forward_gpu_fft(std::vector<caffe::Blob<half_float::half>*, std::allocator<caffe::Blob<half_float::half>*> > const&, std::vector<caffe::Blob<half_float::half>*, std::allocator<caffe::Blob<half_float::half>*> > const&)
```

Having a look in (and around) `conv_layer_fft.cu` reveals there is no instantiation of `Forward_gpu_fft` for `half_float` data types.

**Comment by gongzg** [comment]
Will fix that soon. BTW, FFT layer is recommended, as it hasn't been in active development for a long time. By default, FFT layer is disabled.

**Comment by Bidski** [comment]
So is compiling with `USE_FFT` not recommended?

**Comment by gongzg** [comment]
@Bidski Eaxctly.

**Comment by Bidski** [comment]
This looks like it has fixed the compile errors  on my system
