### ISSUE TITLE
xception fused error

### ISSUE THREAD

**Issue by liyuming1978** [01org/caffe#96]
https://github.com/yihui-he/Xception-caffe/blob/master/trainval.prototxt
I fuse this model, fuse success , but wrong fail (with --proto_only)
the caffe time run error with:
Unknown bottom blob 'interstellar2a_branch2c' (layer 'interstellar2a_branch2c', bottom index 1)

**Comment by gongzg** [comment]
@liyuming1978 I just pushed a patch to fix this bug, please try it out.

**Comment by liyuming1978** [comment]
it's fixed,  after fused the time is 28ms (improved from 50ms to 28ms)
