### ISSUE TITLE
Error when building debug version

### ISSUE THREAD

**Issue by bxk-sonavex** [01org/caffe#97]
I got the following error when building a debug version, using the `build_win.cmd`.  Briefly, the error was `cl : Command line error D8016: '/O1' and '/RTC1' command-line options are incompatible [C:\DL\clCaffe\build\src\caffe\caffe.vcxproj]`.  

The release version was built successfully.  I am using the latest code in the repo, VS 2015 on Intel NUC with iGPU.  Looks this should be a minor fix but I don't know where I should modify.

```
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /IC:\DL\clCaffe\src /IC:\DL\clCaffe\PUBLIC /I"C:\DL\clCaff
  e\build\libraries\include\boost-1_61" /IC:\DL\clCaffe\build\libraries\include /IC:\DL\clCaffe\build\include /IC:\DL\clCaffe\PRIVATE /IC:\
  Intel\OpenCL\sdk\include /IC:\DL\viennacl /IC:\DL\isaac\include\external /IC:\DL\clCaffe\build\libraries\include\opencv /I"C:\Users\NUC-S
  onavex\Anaconda3\envs\py35\include" /I"C:\Users\NUC-Sonavex\Anaconda3\envs\py35\lib\site-packages\numpy\core\include" /IC:\DL\clCaffe\inc
  lude /IC:\DL\clCaffe\build /IC:\DL\clCaffe\build\libraries\Include /Zi /nologo /W3 /WX- /MP /O1 /Ob0 /D WIN32 /D _WINDOWS /D USE_LMDB /D
  USE_LEVELDB /D USE_GREENTEA /D VIENNACL_WITH_OPENCL /D USE_LIBDNN /D USE_INTEL_SPATIAL /D USE_CLBLAS /D HAS_HALF_SUPPORT /D USE_OPENCV /D
   USE_OpenBLAS /D WITH_PYTHON_LAYER /D CAFFE_BUILDING_STATIC_LIB /D CMAKE_WINDOWS_BUILD /D BOOST_ALL_NO_LIB /D "CAFFE_VERSION=1.0.0-rc5" /
  D BOOST_NO_CXX11_TEMPLATE_ALIASES /D USE_HDF5 /D GLOG_NO_ABBREVIATED_SEVERITIES /D "GOOGLE_GLOG_DLL_DECL=__declspec(dllimport)" /D "GOOGL
  E_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport)" /D H5_BUILT_AS_DYNAMIC_LIB=1 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /
  MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"caffe.dir\Debug\\" /Fd"caffe.dir\Debug\caffe.pdb" /Gd /TP /errorReport:qu
  eue C:\DL\clCaffe\build\src\caffe\conv_layer_spatial_pretuned_data.cpp
cl : Command line error D8016: '/O1' and '/RTC1' command-line options are incompatible [C:\DL\clCaffe\build\src\caffe\caffe.vcxproj]
Done Building Project "C:\DL\clCaffe\build\src\caffe\caffe.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\DL\clCaffe\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.


Build FAILED.

... 

"C:\DL\clCaffe\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\DL\clCaffe\build\src\caffe\caffe.vcxproj" (default target) (3) ->
(ClCompile target) ->
  cl : Command line error D8016: '/O1' and '/RTC1' command-line options are incompatible [C:\DL\clCaffe\build\src\caffe\caffe.vcxproj]

    97 Warning(s)
    1 Error(s)
```

I searched the error and found that
>   Run-time error checks are a way for you to find problems in your running code; for more information, see How to: Use Native Run-Time Checks.
>
>    If you compile your program at the command line using any of the /RTC compiler options, any pragma optimize instructions in your code will silently fail. This is because run-time error checks are not valid in a release (optimized) build.
>
>    You should use /RTC for development builds; /RTC should not be used for a retail build. /RTC cannot be used with compiler optimizations (/O Options (Optimize Code)). A program image built with /RTC will be slightly larger and slightly slower than an image built with /Od (up to 5 percent slower than an /Od build).

**Comment by bxk-sonavex** [comment]
I am trying to build debug version using the generated .sln file in VS2015.  When open the Property Pages of the caffe project, it shows that the Optimization is disabled (/Od).  However, I still got the error when building the solution.

**Comment by gongzg** [comment]
@bxk-sonavex confirmed, this is a regression, will fix soon.

**Comment by gongzg** [comment]
just pushed the fix. Please check it again.

**Comment by bxk-sonavex** [comment]
See the place.  It works now.  Thanks for the fix!
